### ISSUE TITLE
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by Komacheee** [minis-patchers/SynWeaponKeywords#25]
After the most recent update to this patcher I keep getting this error, and I've tried everything to rectify it. Restarting, uninstalling and reinstalling .NET, updating to pre release Synthesis, downgrading back down to stable release, nothing seems to fix it. It's on match and my synthesis is up to date. Every other patch works just fine, only this one breaks.

Here's the log:

`Compiling
Extra data folder already exists. Leaving as is: "C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Synth\Data\Skyrim Special Edition\SynWeaponKeywords"
("C:\Users\justi\AppData\Local\Temp\Synthesis\y2m0rfls.l0v\Git\ar442rtw.hqf\Runner\SynPatcher"): "dotnet" "build \"SynPatcher.csproj\" --runtime win-x64 -c Release"
Compiled
Sha "8306c47d99b9b182135c4b41d4e1898e3f3a949b"
Running
(""): "dotnet" "run --project \"C:\Users\justi\AppData\Local\Temp\Synthesis\y2m0rfls.l0v\Git\ar442rtw.hqf\Runner\SynPatcher\SynPatcher.csproj\" --runtime win-x64 -c Release --no-build run-patcher --DataFolderPath \"C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\" --ExtraDataFolder \"C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Synth\Data\Skyrim Special Edition\SynWeaponKeywords\" --DefaultDataFolderPath C:\Users\justi\AppData\Local\Temp\Synthesis\y2m0rfls.l0v\Git\ar442rtw.hqf\Runner\SynPatcher\Data --GameRelease SkyrimSE --ModKey Synthesis.esp --LoadOrderFilePath C:\Users\justi\AppData\Local\Temp\Synthesis\y2m0rfls.l0v\Workspace\Synthesis\Plugins.txt --LoadOrderIncludesCreationClub --OutputPath \"C:\Users\justi\AppData\Local\Temp\Synthesis\y2m0rfls.l0v\Workspace\Synthesis\1 - SynWeaponKeywords\Synthesis.esp\" --PatcherName SynWeaponKeywords --PersistencePath C:\Users\justi\AppData\Local\Temp\Synthesis\y2m0rfls.l0v\Persistence"
Mutagen version: 0.42
Mutagen sha: afe49dc9dffa96892bf34375a76be3e83e55c7b2
Synthesis version: 0.26
Synthesis sha: d4db80a931af636f5a507434220b07363355f719
Newtonsoft version: 13.0.3+0a2e291c0d9c0c7675d445703e51750363a549ef
run-patcher --DataFolderPath "C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data" --ExtraDataFolder "C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Synth\Data\Skyrim Special Edition\SynWeaponKeywords" --DefaultDataFolderPath C:\Users\justi\AppData\Local\Temp\Synthesis\y2m0rfls.l0v\Git\ar442rtw.hqf\Runner\SynPatcher\Data --GameRelease SkyrimSE --ModKey Synthesis.esp --LoadOrderFilePath C:\Users\justi\AppData\Local\Temp\Synthesis\y2m0rfls.l0v\Workspace\Synthesis\Plugins.txt --LoadOrderIncludesCreationClub --OutputPath "C:\Users\justi\AppData\Local\Temp\Synthesis\y2m0rfls.l0v\Workspace\Synthesis\1 - SynWeaponKeywords\Synthesis.esp" --PatcherName SynWeaponKeywords --PersistencePath C:\Users\justi\AppData\Local\Temp\Synthesis\y2m0rfls.l0v\Persistence
Checking runnability
Checking runnability complete
Prepping state.
Language: English
Using TextFileSharedFormKeyAllocator allocator
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Method not found: 'Loqui.ObjectKey Loqui.ILoquiRegistration.get_ObjectKey()'.
   at Mutagen.Bethesda.Oblivion.OblivionAspectInterfaceMapping..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at Mutagen.Bethesda.Plugins.Records.Mapping.AspectInterfaceMapper.AutomaticFactory()
   at Mutagen.Bethesda.Plugins.Records.Mapping.AspectInterfaceMapping.<>c.<.cctor>b__4_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Mutagen.Bethesda.Plugins.Records.Mapping.AspectInterfaceMapping.get_Instance()
   at Mutagen.Bethesda.Plugins.Records.Mapping.MetaInterfaceMapping.<>c.<.cctor>b__4_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Mutagen.Bethesda.Plugins.Records.Mapping.MetaInterfaceMapping.get_Instance()
   at Mutagen.Bethesda.Plugins.Cache.Internals.Implementations.Internal.InternalImmutableLoadOrderLinkCache..ctor(IEnumerable`1 loadOrder, GameCategory gameCategory, Boolean hasAny, Boolean simple, LinkCachePreferences prefs)
   at Mutagen.Bethesda.Plugins.Cache.Internals.Implementations.ImmutableLoadOrderLinkCache`2..ctor(IEnumerable`1 loadOrder, LinkCachePreferences prefs)
   at Mutagen.Bethesda.LinkCacheConstructionMixIn.ToImmutableLinkCache[TMod,TModGetter](ILoadOrderGetter`1 loadOrder, LinkCachePreferences prefs)
   at Mutagen.Bethesda.LinkCacheConstructionMixIn.ToMutableLinkCache[TMod,TModGetter](ILoadOrderGetter`1 immutableBaseCache, TMod[] mutableMods)
   at Mutagen.Bethesda.Synthesis.States.DI.PatcherStateFactory.ToState[TModSetter,TModGetter](RunSynthesisMutagenPatcher settings, PatcherPreferences userPrefs, ModKey exportKey) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\States\DI\PatcherStateFactory.cs:line 56
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Mutagen.Bethesda.Synthesis.States.DI.PatcherStateFactory.ToState(GameCategory category, RunSynthesisMutagenPatcher settings, PatcherPreferences userPrefs, ModKey exportKey) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\States\DI\PatcherStateFactory.cs:line 182
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 628
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass45_0.<<Run>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 496
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.HandleOnShutdown(Func`1 a) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 881
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 484
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass44_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 456

`

**Comment by Minizbot2012** [comment]
Dang, this was showing up during some testing of the update... I need to revert some changes to the csproj to fix this... it's a bug in that particular mutagen version from what I can tell, that's been fixed in the next version... should be fixed now... hopefully

**Comment by Komacheee** [comment]
Unfortunately I'm still getting the same error, though it's smaller now. If that means anything.

`Compiling
Extra data folder already exists. Leaving as is: "C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Synth\Data\Skyrim Special Edition\SynWeaponKeywords"
("C:\Users\justi\AppData\Local\Temp\Synthesis\y2m0rfls.l0v\Git\q2fssxnm.szq\Runner\SynPatcher"): "dotnet" "build \"SynPatcher.csproj\" --runtime win-x64 -c Release"
Compiled
Sha "c1bca1407155113da02cedbfaa5b1974d1c5f2b3"
Running
(""): "dotnet" "run --project \"C:\Users\justi\AppData\Local\Temp\Synthesis\y2m0rfls.l0v\Git\q2fssxnm.szq\Runner\SynPatcher\SynPatcher.csproj\" --runtime win-x64 -c Release --no-build run-patcher --DataFolderPath \"C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\" --ExtraDataFolder \"C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Synth\Data\Skyrim Special Edition\SynWeaponKeywords\" --DefaultDataFolderPath C:\Users\justi\AppData\Local\Temp\Synthesis\y2m0rfls.l0v\Git\q2fssxnm.szq\Runner\SynPatcher\Data --GameRelease SkyrimSE --ModKey Synthesis.esp --LoadOrderFilePath C:\Users\justi\AppData\Local\Temp\Synthesis\y2m0rfls.l0v\Workspace\Synthesis\Plugins.txt --LoadOrderIncludesCreationClub --OutputPath \"C:\Users\justi\AppData\Local\Temp\Synthesis\y2m0rfls.l0v\Workspace\Synthesis\1 - SynWeaponKeywords\Synthesis.esp\" --PatcherName SynWeaponKeywords --PersistencePath C:\Users\justi\AppData\Local\Temp\Synthesis\y2m0rfls.l0v\Persistence"
System.MissingMethodException: Method not found: 'Mutagen.Bethesda.GameCategory Mutagen.Bethesda.GameReleaseExt.ToCategory(Mutagen.Bethesda.GameRelease)'.
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass43_0.<<Run>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 472
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.HandleOnShutdown(Func`1 a) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 833
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 460
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass42_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 432`

Haven't changed anything, and the patcher is still set to match.

**Comment by Minizbot2012** [comment]
Bleh, just reverted most of the changes I made to the C# Project file to revert the formkeys reference as well... Only kept the newtonsoft.json update...

**Comment by Komacheee** [comment]
That seems to have done it as it's working once again, thank you.

**Comment by Minizbot2012** [comment]
Awesome, gonna close this then, for housekeeping reasons :).
